### PR TITLE
Fix CI Badge

### PR DESCRIPTION
**Pull request by floh96**

### CODE REVIEW

**Comment by Xorima** [comment]
Hey @floh96 

Can you add a `CHANGELOG.md` entry under the `## Unreleased` header?

**Comment by floh96** [comment]
@Xorima done

**Review by Xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [12.0.10](https://github.com/sous-chefs/nginx/releases/tag/12.0.10)

**Comment by Xorima** [comment]
Thanks @floh96

**Pull request merged**
