### PR TITLE
Restore fedora support

### PR DESCRIPTION
**Pull request by bmhughes**
# Description

Add Fedora support back to metadata.rb. Massaged a few things to get spec tests to pass.

## Issues Resolved

- None

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bmhughes** [comment]
Rebased on current master

**Comment by Xorima** [comment]
Hey @bmhughes 

Any chance you can rebase this one? Sorry it has taken so long to get around to. 

Note: We have migrated to github actions so you will need to edit `https://github.com/sous-chefs/nginx/blob/master/.github/workflows/ci.yml#L42` instead of the circleci config file

Also thanks again for the help on this :+1:

**Comment by bmhughes** [comment]
Done. The failing tests are failing on master so I've left them alone for now.

**Comment by Xorima** [comment]
not your fault mate, I'll get this merged in,

have you thought about joining sous-chefs org (https://github.com/sous-chefs/terraform-github-org/)?

Thanks again for this 👍

**Comment by bmhughes** [comment]
No problem, glad to help.

I didn't realise what was needed to join, I don't see why not always good to give back!

**Pull request merged**
