### PR TITLE
Add telemetry attributes for Passenger

### PR DESCRIPTION
**Pull request by aried3r**
https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_disable_anonymous_telemetry
https://www.phusionpassenger.com/docs/advanced_guides/in_depth/ruby/anonymous_telemetry_reporting.html

### Description

Adds options to disable anonymous telemetry reporting.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by damacus** [comment]
hey! :) 

can you add a changelog entry for this please

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by aried3r** [comment]
Done!

**Comment by aried3r** [comment]
Thanks for merging!

> I personally try to keep my attributes using the same defaults as the vendor. But the default maintains the behaviour of the previous release

This is the default btw, it _will_ send telemetry unless you turn it off. The previous release (if you mean Passenger 5.x) didn't have telemetry AFAICS, but 6 has it enabled by default.

**Pull request merged**
