### PR TITLE
WIP: Test data / example for nginx_site

### PR DESCRIPTION
**Pull request by ITJamie**
# Description

This gives better test / example data for the cookbook 

## Issues Resolved

https://github.com/sous-chefs/nginx/issues/505

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by ITJamie** [comment]
added a readme update to match the one in apache2 cookbooks readme

**Comment by Xorima** [comment]
Just catching up on this, @ITJamie @damacus @tas50 what do we need to do to get this in?

Having better tests/documentation would be great!

**Comment by Xorima** [comment]
@ITJamie could you resolve the conflicts then I will just merge this in?

It's documentation only so failing tests are not your fault

**Comment by damacus** [comment]
Hey @ITJamie have you had any more time to look at this one?

Thanks
Sous-Chefs

**Comment by MarkGibbons** [comment]
#549 includes this change and is rebased.

**Pull request closed without merging**
