### PR TITLE
487/boolean

### LINKED ISSUE #487: Cleanup: Remove backward compatibility hacks
# Brief Description

There are several hacks/messy thing that allow for multiple types e.g. 

https://github.com/sous-chefs/nginx/blob/master/resources/site.rb#L5

## Acceptance Criteria 

`[TrueClass,FalseClass]` is used instead of any strings.

### PR DESCRIPTION
**Pull request by damacus**
# Description

Remove section in site resource that is deprecated

## Issues Resolved

Fixes #487 

## Check List

- [ ] All tests pass. See TESTING.md for details
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
This totally borks the unit tests. 

Those need to be restructured, to use the more modern form. 🤔 

I think that we probably need to rethink this whole cookbook from ground up. And in the process rethink how we're doing unit testing.

**Comment by Xorima** [comment]
How and what should we be doing in unit testing, I can bring across the apache2 tests but it's resource only, is that good enough for now and we just accept that recipes are going and we do not have tests for them at this moment in time?

**Comment by damacus** [comment]
Closing in favour of #492

**Comment by damacus** [comment]
The biggest reason have the apache tests are there are to help with developing the correct resources and libraries.

**Pull request closed without merging**
