### PR TITLE
Fix doc nginx site

### PR DESCRIPTION
**Pull request by schaerli**
# Description

Documentation change

## Issues Resolved

none

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by jeffbyrnes — DISMISSED** [review]

**Comment by jeffbyrnes** [comment]
That delivery failure appears to be Linux distro drift unrelated to this change.

**Comment by damacus** [comment]
@schaerli would you be able to fix that OS version issue in the tests in this PR or shall we spin it out into a new PR?

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [12.0.8](https://github.com/sous-chefs/nginx/releases/tag/12.0.8)

**Comment by schaerli** [comment]
@damacus i tried it here but i dont know if this is correct, i only update the spec https://github.com/sous-chefs/nginx/pull/598

**Pull request merged**
